###############################################################################
#   @author         :   Jeffrey Stone 
#   @date           :   02/19/2019
#   @package        :   Daily
#   @description    :   Maint Automation that occurs every day
###############################################################################
automation:
  # Using the HACS Daily Snapshot Clean Up Plugin 
  - id: daily_snapshot_clean_up
    alias: Daily snapshot clean up
    initial_state: 'on'
    trigger: 
    - platform: time
      at: '03:00:00'
    condition:
    action:
      - service: clean_up_snapshots_service.clean_up

  # Nightly Entity Refresh - For all those sensors that need a little push
  - id: daily_entity_refresh
    alias: Daily Entity Refresh
    initial_state: 'on'
    trigger: 
    - platform: time
      at: '00:01:45'
    condition:
    action:
      - service: homeassistant.update_entity
        entity_id: sensor.today_is 
  
    