###############################################################################
#   @author         :   Jeffrey Stone 
#   @date           :   07/09/2019
#   @package        :   Jarvis
#   @description    :   Bringing some Jarvis to Home Assistant
###############################################################################

input_boolean:
  house_party_protocol:
    name: House Party Protocol

automation:
  - id: house_party_protocol_on
    alias: Turn On House Party Protocol
    initial_state: true
    trigger:
    - platform: state
      entity_id: input_boolean.house_party_protocol
      to: 'on'
    action:
    - service: homeassistant.turn_on
      entity_id: group.incense
    - service: script.jarvis_voice
      data_template:
        who: '{{ states.sensor.room_audio.state }}'
        message: >
        <p>
          {{ [
            'Anchorage House has been configured for a House Party.',
            'Incense has been turned on.',
            'I have enabled house party protocol.'
            ] | random }}
        </p>
  
  - id: house_party_protocol_off
    alias: Turn Off House Party Protocol
    initial_state: true
    trigger:
    - platform: state
      entity_id: input_boolean.house_party_protocol
      to: 'off'
    action:
    - service: homeassistant.turn_off
      entity_id: group.incense
    - service: script.jarvis_voice
      data_template:
        who: '{{ states.sensor.room_audio.state }}'
        message: >
        <p>
          {{ [
            'The House Party has been canceled.',
            'Incense has been turned off.',
            'I have disabled house party protocol.'
            ] | random }}
        </p>
