washer_finished_notification_audible:
  sequence:
  - delay:
      minutes: 15
  - condition: state
    entity_id: sensor.family_status
    state: Home
  - condition: state
    entity_id: sensor.washer_status
    state: complete
  - service: script.ah_report
    data:
      call_interuption: 1
      call_washer_needs_emptying: 1
  - service: input_boolean.turn_on
    entity_id: input_boolean.washer_finished
  - delay:
      minutes: 15
  - condition: state
    entity_id: sensor.family_status
    state: Home
  - condition: state
    entity_id: sensor.washer_status
    state: complete
  - service: script.ah_report
    data:
      call_interuption: 1
      call_washer_needs_emptying: 1
  - delay:
      minutes: 15
  - condition: state
    entity_id: sensor.family_status
    state: Home
  - condition: state
    entity_id: sensor.washer_status
    state: complete
  - service: script.ah_report
    data:
      call_interuption: 1
      call_washer_needs_emptying: 1
  

washer_idle:
  sequence:
  - service: mqtt.publish
    data:
      topic: house/washer/status
      payload: idle
      retain: true
washer_running:
  sequence:
  - service: mqtt.publish
    data:
      topic: house/washer/status
      payload: running
      retain: true
washer_complete:
  sequence:
  - service: mqtt.publish
    data:
      topic: house/washer/status
      payload: complete
      retain: true

reset_ha_speaker:
  sequence:
  - delay:
      seconds: 30
  - service: switch.turn_off
    entity_id: switch.ha_speaker