#########################################
#
# Light Based Scripts
#
#########################################


##########################
# Dim Living Room lights slowly - Sengled Bulbs - No Built in Transistion. 
# Script can take a delay, if no delay is passed delay is set to 5
# delay should be in seconds
# Script takes the following
# entity_id = The light you want to fade in
# transition: = # Seconds to go from current to end brightness
# brightness_pct: = # Brightness to end at as a percentage
lr_sengled_transistion_on:
  sequence: 
  - service: python_script.light_transistion
    data:
      entity_id: light.tower_lamp_2
      brightness_pct: 100
      transition: 60

lr_sengled_transistion_off:
  sequence: 
  - service: python_script.light_transistion
    data:
      entity_id: light.tower_lamp_2
      brightness_pct: 0
      transition: 60

# Turn on Living Room Lights if sun is down or cloud coverage is above 70%
livingroom_lamps_on:
  sequence:
  - condition: or
    conditions:
      - condition: state  
        entity_id: sun.sun
        state: 'below_horizon'
  - service: scene.turn_on 
    entity_id: scene.normal_livingroom_lighting

# Turn off Living Room Lights if sun is up and cloud coverage is below 70%
livingroom_lamps_off:
  sequence:
  - condition: and
    conditions:
      - condition: state  
        entity_id: sun.sun
        state: 'above_horizon'
  - service: group.turn_off 
    entity_id: group.livingroom_lamps
  
