- platform: mqtt
  name: "Battery Front Door Sensor"
  state_topic: "zwave2mqtt/front_door_sensor/128/1/0"
  unit_of_measurement: "%"
  device_class: battery
  value_template: "{{ value }}"
  json_attributes_topic: "zwave2mqtt/front_door_sensor/128/1/0"
- platform: mqtt
  name: "Battery Laundry Door Sensor"
  state_topic: "zwave2mqtt/laundry_door_sensor/128/1/0"
  unit_of_measurement: "%"
  device_class: battery
  value_template: "{{ value }}"
  json_attributes_topic: "zwave2mqtt/laundry_door_sensor/128/1/0"
- platform: mqtt
  name: "Battery Kitchen Smoke Detector"
  state_topic: "zwave2mqtt/kitchen_detector/128/1/0"
  unit_of_measurement: "%"
  device_class: battery
  value_template: "{{ value }}"
  json_attributes_topic: "zwave2mqtt/kitchen_detector/128/1/0"
- platform: mqtt
  name: "Battery Garage Smoke Detector"
  state_topic: "zwave2mqtt/garage_detector/128/1/0"
  unit_of_measurement: "%"
  device_class: battery
  value_template: "{{ value }}"
  json_attributes_topic: "zwave2mqtt/garage_detector/128/1/0"
- platform: mqtt
  name: "Battery Attic Door Sensor"
  state_topic: "zwave2mqtt/attic_door/128/1/0"
  unit_of_measurement: "%"
  device_class: battery
  value_template: "{{ value }}"
  json_attributes_topic: "zwave2mqtt/attic_door/128/1/0"
- platform: mqtt
  name: "Battery Washer Door Sensor"
  state_topic: "zwave2mqtt/washer_door_sensor/128/1/0"
  unit_of_measurement: "%"
  device_class: battery
  value_template: "{{ value }}"
  json_attributes_topic: "zwave2mqtt/washer_door_sensor/128/1/0"
- platform: mqtt
  name: "Battery Back Door Sensor"
  state_topic: "zwave2mqtt/back_door_sensor/128/1/0"
  unit_of_measurement: "%"
  device_class: battery
  value_template: "{{ value }}"
  json_attributes_topic: "zwave2mqtt/back_door_sensor/128/1/0"
- platform: mqtt
  name: "Battery Side Door Sensor"
  state_topic: "zwave2mqtt/side_door_sensor/128/1/0"
  unit_of_measurement: "%"
  device_class: battery
  value_template: "{{ value }}"
  json_attributes_topic: "zwave2mqtt/side_door_sensor/128/1/0"
- platform: mqtt
  name: "Battery Garage Door Sensor"
  state_topic: "zwave2mqtt/garage_door/128/1/0"
  unit_of_measurement: "%"
  device_class: battery
  value_template: "{{ value }}"
  json_attributes_topic: "zwave2mqtt/garage_door/128/1/0"
- platform: mqtt 
  name: "Battery Garage Motion Sensor"
  state_topic: "zwave2mqtt/garage_motion/128/1/0"
