- platform: mqtt
  name: "Front Door Battery"
  state_topic: "zwave2mqtt/front_door/128/1/0"
  unit_of_measurement: "%"
  device_class: battery
  value_template: "{{ value }}"
  json_attributes_topic: "zwave2mqtt/front_door/128/1/0"
- platform: mqtt
  name: "Laundry Door Battery"
  state_topic: "zwave2mqtt/laundry_room/128/1/0"
  unit_of_measurement: "%"
  device_class: battery
  value_template: "{{ value }}"
  json_attributes_topic: "zwave2mqtt/laundry_room/128/1/0"
- platform: mqtt
  name: "Kitchen Smoke Battery"
  state_topic: "zwave2mqtt/nodeID_19/128/1/0"
  unit_of_measurement: "%"
  device_class: battery
  value_template: "{{ value }}"
  json_attributes_topic: "zwave2mqtt/nodeID_19/128/1/0"
- platform: mqtt
  name: "Attic Door Battery"
  state_topic: "zwave2mqtt/attic_door/128/1/0"
  unit_of_measurement: "%"
  device_class: battery
  value_template: "{{ value }}"
  json_attributes_topic: "zwave2mqtt/attic_door/128/1/0"
- platform: mqtt
  name: "Washer Door Battery"
  state_topic: "zwave2mqtt/washer_door/128/1/0"
  unit_of_measurement: "%"
  device_class: battery
  value_template: "{{ value }}"
  json_attributes_topic: "zwave2mqtt/washer_door/128/1/0"
- platform: mqtt
  name: "Back Door Battery"
  state_topic: "zwave2mqtt/back_door/128/1/0"
  unit_of_measurement: "%"
  device_class: battery
  value_template: "{{ value }}"
  json_attributes_topic: "zwave2mqtt/back_door/128/1/0"
- platform: mqtt
  name: "Side Door Battery"
  state_topic: "zwave2mqtt/side_door/128/1/0"
  unit_of_measurement: "%"
  device_class: battery
  value_template: "{{ value }}"
  json_attributes_topic: "zwave2mqtt/side_door/128/1/0"
- platform: mqtt
  name: "Garage Door Battery"
  state_topic: "zwave2mqtt/garage_door/128/1/0"
  unit_of_measurement: "%"
  device_class: battery
  value_template: "{{ value }}"
  json_attributes_topic: "zwave2mqtt/garage_door/128/1/0"
- platform: mqtt 
  name: "Garage Motion Battery"
  state_topic: "zwave2mqtt/garage_motion/128/1/0"
- platform: mqtt
  name: "Dome Alarm"
  state_topic: "zwave2mqtt/dome_alarm/128/1/0"