- platform: waze_travel_time
  name: "Jeff ETT Home"
  #api_key: !secret google_api
  origin: device_tracker.jeffreys_iphone_11
  destination: zone.home
  region: 'US'
- platform: waze_travel_time
  name: "Kat ETT Home"
  #api_key: !secret google_api
  origin: device_tracker.life360_kat_stone
  destination: zone.home
  region: 'US'
- platform: waze_travel_time
  name: "Home To Summit"
#  api_key: !secret google_api
  origin: zone.home
  destination: zone.summit
  region: 'US'
- platform: waze_travel_time
  name: "Home To Zoo"
#  api_key: !secret google_api#
  origin: zone.home
  destination: zone.zoo_atlanta
  region: 'US'
