# REMOVING Darksky - Commented out to disable.
# - platform: darksky
#   api_key: !secret FORCAST_API_KEY
#   forecast:
#     - 0
#   monitored_conditions:
#     - summary
#     - icon
#     - nearest_storm_distance
#     - nearest_storm_bearing
#     - precip_type
#     - precip_intensity
#     - precip_probability
#     - temperature
#     - temperature_high
#     - temperature_low
#     - apparent_temperature
#     - dew_point
#     - wind_speed
#     - wind_bearing
#     - cloud_cover
#     - humidity
#     - pressure
#     - visibility
#     - ozone
#     - minutely_summary
#     - hourly_summary
#     - daily_summary
#     - precip_intensity_max
#   scan_interval:
#     # At least one of these must be specified:
#     days: 0
#     hours: 0
#     minutes: 5
#     seconds: 0
#     milliseconds: 0
## Accurite 158 - Back Porch
- platform: mqtt
  name: "Accurite Back Porch Temperature"
  state_topic: "house/accurite-158/temperature"
  device_class: temperature
- platform: mqtt
  name: "Accurite Back Porch Humidity"
  state_topic: "house/accurite-158/humidity"

# - platform: mqtt
#   name: "Accurite Back Porch Status"
#   state_topic: "house/accurite-158/status"
# - platform: mqtt
#   name: "Accurite Back Porch Battery"
#   state_topic: "house/accurite-158/battery"
- platform: mqtt
  name: "Accurite Back Porch Model"
  state_topic: "house/accurite-158/model"
- platform: mqtt
  name: "Accurite Back Porch lupdate"
  state_topic: "house/accurite-158/lastupdate"
- platform: mqtt
  name: "Accurite Garage Temperature"
  state_topic: "house/accurite-10968/temperature"
  device_class: temperature
- platform: mqtt
  name: "Accurite Garage Humidity"
  state_topic: "house/accurite-10968/humidity"
- platform: mqtt
  name: "Accurite Garage Model"
  state_topic: "house/accurite-10968/model"
- platform: mqtt
  name: "Accurite Garage lupdate"
  state_topic: "house/accurite-10968/lastupdate"

- platform: statistics
  name: Inside Humidity Stats
  entity_id: sensor.current_inside_humidity
  sampling_size: 500

- platform: template
  sensors:
    clothing_forecast:
      friendly_name: "Clothing Forecast"
      unit_of_measurement: ''
      value_template: >-
          {%- if states('sensor.nws_daytime_temperature')|float > 63 %}
            {%- if states('sensor.nws_daytime_temperature')|float < 80 %}
              Nice
            {% elif states('sensor.nws_daytime_temperature')|float > 95 %}
              Hot
            {% else %}
              Toasty
            {%- endif %}
          {% elif states('sensor.nws_daytime_temperature')|float < 64 %}
            {%- if states('sensor.nws_daytime_temperature')|float < 32 %}
              Freezing
            {% elif states('sensor.nws_daytime_temperature')|float > 50 %}
              Chilly
            {% else %}
              Cold
            {%- endif %}
          {% else %}
           Unknown
          {%- endif %}
    nws_current_forecast:
      friendly_name: 'Current Forecast'
      value_template: "{{ states.weather.klzu.attributes.forecast[0].detailed_description | truncate(250, False) }}"
    nws_current_rain_forecast:
      friendly_name: 'Current Rain Chance'
      value_template: "{{ states.weather.klzu.attributes.forecast[0].precipitation_probability }}"
      unit_of_measurement: '%'
    nws_current_temperature:
      friendly_name: 'Current Temperature'
      value_template: "{{ states.weather.klzu.attributes.temperature }}"
      device_class: temperature
    nws_daytime_temperature:
      friendly_name: 'Daytime Temperature'
      value_template: >-
          {% if states.weather.klzu.attributes.forecast[0].daytime == True %}
            {{ states.weather.klzu.attributes.forecast[0].temperature }}
          {% elif states.weather.klzu.attributes.forecast[1].daytime == True %}
            {{ states.weather.klzu.attributes.forecast[1].temperature }}
          {% endif %}
      device_class: temperature
    nws_current_condition: 
      friendly_name: 'Current Condition'
      value_template: "{{ states.weather.klzu.state }}"
    nws_current_humidity:
      friendly_name: 'Current Humidity'
      value_template: "{{ states.weather.klzu.attributes.humidity }}"
    nws_current_visibility:
      friendly_name: "Current Visability"
      value_template: "{{ states.weather.klzu.attributes.visibility }}"
    nws_current_windspeed:
      friendly_name: "Current Windspeed"
      value_template: "{{ states.weather.klzu.attributes.wind_speed }}"
    nws_overnight_low:
      friendly_name: "Overnight Low"
      unit_of_measurement: ''
      value_template: >-
          {% if states.weather.klzu.attributes.forecast[0].daytime == False %}
            {{ states.weather.klzu.attributes.forecast[0].temperature }}
          {% elif states.weather.klzu.attributes.forecast[1].daytime == False %}
            {{ states.weather.klzu.attributes.forecast[1].temperature }}
          {% endif %}
    nws_overnight_forecast:
      friendly_name: "Overnight Forecast"
      unit_of_measurement: ''
      value_template: >-
          {% if states.weather.klzu.attributes.forecast[0].daytime == False %}
            {{ states.weather.klzu.attributes.forecast[0].detailed_description | truncate(250, False) }}
          {% elif states.weather.klzu.attributes.forecast[1].daytime == False %}
            {{ states.weather.klzu.attributes.forecast[1].detailed_description | truncate(250, False) }}
          {% elif states.weather.klzu.attributes.forecast[2].daytime == False %}
            {{ states.weather.klzu.attributes.forecast[2].detailed_description | truncate(250, False) }}
          {% endif %}
    nws_forecast_tomorrow:
      friendly_name: "Forecast Tomorrow"
      unit_of_measurement: ''
      value_template: >-
          {%- if states.weather.klzu.attributes.forecast[1].daytime == True %}
            {{ states.weather.klzu.attributes.forecast[1].detailed_description | truncate(250, False) }} 
          {% elif states.weather.klzu.attributes.forecast[2].daytime == True %}
            {{ states.weather.klzu.attributes.forecast[2].detailed_description | truncate(250, False) }} 
          {%- endif %}
    nws_forecast_rain_tomorrow:
      friendly_name: "Rain Chance Tomorrow"
      unit_of_measurement: '%'
      value_template: >-
          {%- if states.weather.klzu.attributes.forecast[1].daytime == True %}
            {{ states.weather.klzu.attributes.forecast[1].precipitation_probability }} 
          {% elif states.weather.klzu.attributes.forecast[2].daytime == True %}
            {{ states.weather.klzu.attributes.forecast[2].precipitation_probability }} 
          {%- endif %}
    nws_forecast_tomorrow_night:
      friendly_name: "Forecast Tomorrow Night"
      unit_of_measurement: ''
      value_template: >-
          {%- if states.weather.klzu.attributes.forecast[1].daytime == True %}
            {{ states.weather.klzu.attributes.forecast[2].detailed_description | truncate(250, False) }} 
          {% elif states.weather.klzu.attributes.forecast[2].daytime == True %}
            {{ states.weather.klzu.attributes.forecast[3].detailed_description | truncate(250, False) }}
          {%- endif %}
    nws_forecast_rain_tomorrow_night:
      friendly_name: "Rain Chance Tomorrow Night"
      unit_of_measurement: '%'
      value_template: >-
          {%- if states.weather.klzu.attributes.forecast[1].daytime == True %}
            {{ states.weather.klzu.attributes.forecast[2].precipitation_probability  }} 
          {% elif states.weather.klzu.attributes.forecast[2].daytime == True %}
            {{ states.weather.klzu.attributes.forecast[3].precipitation_probability  }}
          {%- endif %}
    current_inside_humidity:
      friendly_name: "Current Inside Humidity"
      unit_of_measurement: '%'
      value_template: "{{ states.climate.home.attributes.current_humidity }}"