# REMOVING Darksky - Commented out to disable.
# - platform: darksky
#   api_key: !secret FORCAST_API_KEY
#   forecast:
#     - 0
#   monitored_conditions:
#     - summary
#     - icon
#     - nearest_storm_distance
#     - nearest_storm_bearing
#     - precip_type
#     - precip_intensity
#     - precip_probability
#     - temperature
#     - temperature_high
#     - temperature_low
#     - apparent_temperature
#     - dew_point
#     - wind_speed
#     - wind_bearing
#     - cloud_cover
#     - humidity
#     - pressure
#     - visibility
#     - ozone
#     - minutely_summary
#     - hourly_summary
#     - daily_summary
#     - precip_intensity_max
#   scan_interval:
#     # At least one of these must be specified:
#     days: 0
#     hours: 0
#     minutes: 5
#     seconds: 0
#     milliseconds: 0
## Accurite 158 - Crawlspace
- platform: mqtt
  name: "Crawlspace Temperature"
  state_topic: "house/acurite-158/temperature"
  device_class: temperature
- platform: mqtt
  name: "Crawlspace Humidity"
  state_topic: "house/acurite-158/humidity"
  device_class: humidity
- platform: mqtt
  name: "Crawlspace Model"
  state_topic: "house/acurite-158/model"
- platform: mqtt
  name: "Crawlspace lupdate"
  state_topic: "house/acurite-158/last_update"
  device_class: timestamp

## Accurite 10968 - Garage
- platform: mqtt
  name: "Garage Temperature"
  state_topic: "house/acurite-10968/temperature"
  device_class: temperature
- platform: mqtt
  name: "Garage Humidity"
  state_topic: "house/acurite-10968/humidity"
  device_class: humidity
- platform: mqtt
  name: "Garage Model"
  state_topic: "house/acurite-10968/model"
- platform: mqtt
  name: "Garage lupdate"
  state_topic: "house/acurite-10968/last_update"
  device_class: timestamp


## Accurite 6045M - Back Porch
- platform: mqtt
  name: "Back Porch Temperature"
  state_topic: "house/acurite-6045M/temperature"
  device_class: temperature
- platform: mqtt
  name: "Back Porch Humidity"
  state_topic: "house/acurite-6045M/humidity"
  device_class: humidity
- platform: mqtt
  name: "Back Porch Model"
  state_topic: "house/acurite-6045M/model"
- platform: mqtt
  name: "Back Porch lupdate"
  state_topic: "house/acurite-6045M/last_update"
  device_class: timestamp
- platform: mqtt
  name: "Lightning Strike Count"
  state_topic: "house/acurite-6045M/lightning_count"
- platform: mqtt
  name: "Lightning Storm Distance"
  state_topic: "house/acurite-6045M/storm_dist"

- platform: mqtt
  name: "Lightning total count"
  state_topic: "house/lightning/total_count"



- platform: statistics
  name: Inside Humidity Stats
  entity_id: sensor.current_inside_humidity
  sampling_size: 500

- platform: template
  sensors:
    clothing_forecast:
      friendly_name: "Clothing Forecast"
      unit_of_measurement: ''
      entity_id: sensor.nws_daytime_temperature
      value_template: >-
          {%- if states('sensor.nws_daytime_temperature')|float > 63 %}
            {%- if states('sensor.nws_daytime_temperature')|float < 80 %}
              Nice
            {% elif states('sensor.nws_daytime_temperature')|float > 95 %}
              Hot
            {% else %}
              Toasty
            {%- endif %}
          {% elif states('sensor.nws_daytime_temperature')|float < 64 %}
            {%- if states('sensor.nws_daytime_temperature')|float < 32 %}
              Freezing
            {% elif states('sensor.nws_daytime_temperature')|float > 50 %}
              Chilly
            {% else %}
              Cold
            {%- endif %}
          {% else %}
           Unknown
          {%- endif %}
    nws_current_forecast:
      friendly_name: 'Current Forecast'
      entity_id: weather.klzu_daynight
      value_template: "{{ states.weather.klzu_daynight.attributes.forecast[0].detailed_description | truncate(250, False) }}"
    nws_current_rain_forecast:
      friendly_name: 'Current Rain Chance'
      entity_id: weather.klzu_daynight
      value_template: "{{ states.weather.klzu_daynight.attributes.forecast[0].precipitation_probability }}"
      unit_of_measurement: '%'
    nws_current_temperature:
      friendly_name: 'Current Temperature'
      entity_id: weather.klzu_daynight
      value_template: "{{ states.weather.klzu_daynight.attributes.temperature }}"
      device_class: temperature
    nws_daytime_temperature:
      friendly_name: 'Daytime Temperature'
      entity_id: weather.klzu_daynight
      value_template: >-
          {% if states.weather.klzu_daynight.attributes.forecast[0].daytime == True %}
            {{ states.weather.klzu_daynight.attributes.forecast[0].temperature }}
          {% elif states.weather.klzu_daynight.attributes.forecast[1].daytime == True %}
            {{ states.weather.klzu_daynight.attributes.forecast[1].temperature }}
          {% endif %}
      device_class: temperature
    nws_current_condition: 
      friendly_name: 'Current Condition'
      entity_id: weather.klzu_daynight
      value_template: "{{ states.weather.klzu_daynight.state }}"
    nws_current_humidity:
      friendly_name: 'Current Humidity'
      entity_id: weather.klzu_daynight
      value_template: "{{ states.weather.klzu_daynight.attributes.humidity }}"
    nws_current_visibility:
      friendly_name: "Current Visability"
      entity_id: weather.klzu_daynight
      value_template: "{{ states.weather.klzu_daynight.attributes.visibility }}"
    nws_current_windspeed:
      friendly_name: "Current Windspeed"
      entity_id: weather.klzu_daynight
      value_template: "{{ states.weather.klzu_daynight.attributes.wind_speed }}"
    nws_overnight_low:
      friendly_name: "Overnight Low"
      entity_id: weather.klzu_daynight
      unit_of_measurement: ''
      value_template: >-
          {% if states.weather.klzu_daynight.attributes.forecast[0].daytime == False %}
            {{ states.weather.klzu_daynight.attributes.forecast[0].temperature }}
          {% elif states.weather.klzu_daynight.attributes.forecast[1].daytime == False %}
            {{ states.weather.klzu_daynight.attributes.forecast[1].temperature }}
          {% endif %}
    nws_overnight_forecast:
      friendly_name: "Overnight Forecast"
      entity_id: weather.klzu_daynight
      unit_of_measurement: ''
      value_template: >-
          {% if states.weather.klzu_daynight.attributes.forecast[0].daytime == False %}
            {{ states.weather.klzu_daynight.attributes.forecast[0].detailed_description | truncate(250, False) }}
          {% elif states.weather.klzu_daynight.attributes.forecast[1].daytime == False %}
            {{ states.weather.klzu_daynight.attributes.forecast[1].detailed_description | truncate(250, False) }}
          {% elif states.weather.klzu_daynight.attributes.forecast[2].daytime == False %}
            {{ states.weather.klzu_daynight.attributes.forecast[2].detailed_description | truncate(250, False) }}
          {% endif %}
    nws_forecast_tomorrow:
      friendly_name: "Forecast Tomorrow"
      entity_id: weather.klzu_daynight
      unit_of_measurement: ''
      value_template: >-
          {%- if states.weather.klzu_daynight.attributes.forecast[1].daytime == True %}
            {{ states.weather.klzu_daynight.attributes.forecast[1].detailed_description | truncate(250, False) }} 
          {% elif states.weather.klzu_daynight.attributes.forecast[2].daytime == True %}
            {{ states.weather.klzu_daynight.attributes.forecast[2].detailed_description | truncate(250, False) }} 
          {%- endif %}
    nws_forecast_rain_tomorrow:
      friendly_name: "Rain Chance Tomorrow"
      entity_id: weather.klzu_daynight
      unit_of_measurement: '%'
      value_template: >-
          {%- if states.weather.klzu_daynight.attributes.forecast[1].daytime == True %}
            {{ states.weather.klzu_daynight.attributes.forecast[1].precipitation_probability }} 
          {% elif states.weather.klzu_daynight.attributes.forecast[2].daytime == True %}
            {{ states.weather.klzu_daynight.attributes.forecast[2].precipitation_probability }} 
          {%- endif %}
    nws_forecast_tomorrow_night:
      friendly_name: "Forecast Tomorrow Night"
      entity_id: weather.klzu_daynight
      unit_of_measurement: ''
      value_template: >-
          {%- if states.weather.klzu_daynight.attributes.forecast[1].daytime == True %}
            {{ states.weather.klzu_daynight.attributes.forecast[2].detailed_description | truncate(250, False) }} 
          {% elif states.weather.klzu_daynight.attributes.forecast[2].daytime == True %}
            {{ states.weather.klzu_daynight.attributes.forecast[3].detailed_description | truncate(250, False) }}
          {%- endif %}
    nws_forecast_rain_tomorrow_night:
      friendly_name: "Rain Chance Tomorrow Night"
      entity_id: weather.klzu_daynight
      unit_of_measurement: '%'
      value_template: >-
          {%- if states.weather.klzu_daynight.attributes.forecast[1].daytime == True %}
            {{ states.weather.klzu_daynight.attributes.forecast[2].precipitation_probability  }} 
          {% elif states.weather.klzu_daynight.attributes.forecast[2].daytime == True %}
            {{ states.weather.klzu_daynight.attributes.forecast[3].precipitation_probability  }}
          {%- endif %}
    current_inside_humidity:
      friendly_name: "Current Inside Humidity"
      entity_id: climate.home
      unit_of_measurement: '%'
      value_template: "{{ states.climate.home.attributes.current_humidity }}"
  