
- id: upstairs_fan_on
  alias: Upstairs Fan On
  initial_state: true
  trigger:
  - entity_id: binary_sensor.upstairs_occupancy
    from: 'Off'
    platform: state
    to: 'On'
  condition:
  - above: 73
    condition: numeric_state
    entity_id: sensor.upstairs_temperature
  action:
  - data:
      entity_id: switch.upstairs_fan
    service: switch.turn_on
  

- id: '1562066108032'
  alias: Living Room Fan On
  initial_state: true
  trigger:
  - entity_id: binary_sensor.living_room_occupancy
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.livingroom_fan
    state: 'off'
  - above: 73
    condition: numeric_state
    entity_id: sensor.living_room_temperature
  action:
  - data:
      entity_id: switch.livingroom_fan
    service: switch.turn_on
- id: '1562067639239'
  alias: Upstairs Fan Off
  initial_state: true
  trigger:
  - entity_id: binary_sensor.upstairs_occupancy
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: switch.croft_fan
    state: 'on'
  - below: 72
    condition: numeric_state
    entity_id: sensor.upstairs_temperature
  action:
  - data:
      entity_id: switch.croft_fan
    service: switch.turn_off



# - id: turn_off_ha_speaker
#   alias: Turn Off HA Speaker
#   trigger:
#   - platform: state
#     entity_id: media_player.hass_speaker
#     from: 'playing'
#     to: 'idle'
#   action:
#   - service: media_player.turn_off
#     entity_id: media_player.hass_speaker
#   initial_state: true

- id: turn_off_kitchen_speaker
  alias: Turn Off Kitchen Display
  trigger:
  - platform: state
    entity_id: media_player.googlehomehub3492
    from: 'playing'
    to: 'idle'
  action:
  - service: media_player.turn_off
    entity_id: media_player.googlehomehub3492
  initial_state: true

# - id: turn_off_ha_speaker
#   alias: Turn Off HA Speaker
#   trigger:
#   - platform: state
#     entity_id: media_player.ha_speaker
#     from: 'playing'
#     to: 'idle'
#   action:
#   - service: switch.turn_off
#     entity_id: switch.ha_speaker
#   - service: media_player.turn_off
#     entity_id: media_player.ha_speaker
#   - service: script.kill_this_ride
#   initial_state: true

# - id: save_old_covid_stats
#   alias: Old Covid Stats archive
#   trigger:
#   - platform: time
#     at: '15:12:15'
#   action:
#   - service: script.save_old_covid_stats
#   initial_state: true

- id: kitchen_occupency_lighting
  alias: Kitchen Occupency Lighting
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_motion
    to: 'on'
  action:
  - service: script.dog_mode_on
  - service: script.kitchen_lights_on
  - service: script.kitchen_lights_night
  

- id: driveway_motion_lighting
  alias: Driveway Motion Lighting 
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.aarlo_motion_driveway
    to: 'on'
  condition:
  - condition: state  
    entity_id: sun.sun
    state: 'below_horizon'
  action:
  - service: switch.turn_on
    entity_id: switch.driveway_light
  - delay:
      minutes: 3
  - service: switch.turn_off
    entity_id: switch.driveway_light
  


# - id: show_time
#   alias: Show Time
#   initial_state: true
#   trigger:
#   - platform: state
#     entity_id: media_player.home_theater
#     to: 'playing'
#   condition:
#   - condition: state  
#     entity_id: light.theater_light
#     state: 'on'
#   action:
#   - service: script.turn_on
#     entity_id: script.theater_lights_down
#   - service: script.turn_off
#     entity_id: script.theater_lights_up

# - id: show_time start paused
#   alias: Show Time Start Paused
#   initial_state: true
#   trigger:
#   - platform: state
#     entity_id: media_player.home_theater
#     to: 'idle'
#   condition:
#   - condition: state  
#     entity_id: script.theater_lights_down
#     state: 'on'
#   action:
#   - service: script.turn_off
#     entity_id: script.theater_lights_down
  
- id: show_time_over
  alias: Show Time over
  initial_state: true
  trigger:
  - platform: state
    entity_id: media_player.theater_tv
    to: 'off'
    for: 
      minutes: 20
  action:
  - service: scene.turn_on
    entity_id: scene.theater_dark

- id: theater_fan_on
  alias: Theater Fan On 
  initial_state: true
  trigger:
  - above: 74
    platform: numeric_state
    entity_id: sensor.theater_temperature
  condition: 
    - condition: state
      entity_id: media_player.theater_tv
      state: 'on'
  action:
  - data:
      entity_id: switch.theater_fan
    service: switch.turn_on

- id: theater_fan_off
  alias: Theater Fan Off 
  initial_state: true
  trigger:
  - below: 72
    platform: numeric_state
    entity_id: sensor.theater_temperature
  condition: 
    - condition: state
      entity_id: media_player.theater_tv
      state: 'off'
  action:
  - data:
      entity_id: switch.theater_fan
    service: switch.turn_on

- id: theater_light_pressed_up
  alias: Theater Light Pressed Up
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.theater_light_up
  action:
  - service: scene.turn_on
    entity_id: scene.theater_bright

- id: theater_light_pressed_down
  alias: Theater Light Pressed Down
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.theater_light_down
  action:
  - service: scene.turn_on
    entity_id: scene.theater_dark
