homeassistant:
  name: Home
  latitude: !secret MY_LATITUDE
  longitude: !secret MY_LONGITUDE
  elevation: 315
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
  packages: !include_dir_named packages


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret ahsl_base_url
  ssl_certificate: !secret ahsl_ssl_cert
  ssl_key: !secret ahsl_ssl_key
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.7.1
    - 162.158.187.228
    - 162.158.187.182
    - 108.162.238.38
    - 172.68.65.205
  ip_ban_enabled: true
  login_attempts_threshold: 5

ssdp:

zeroconf:

system_health:

mobile_app:

person:

frontend:
  themes: !include_dir_merge_named themes

# Text to speech
# tts:
#   - platform: google_translate

cloud:
  
wemo:
  discovery: true
  static:
  - 192.168.7.99

weather:
  # REMOVING darksky integration since API is EOL in 18 months. Migrated to NWS
  # - platform: darksky
  #   api_key: !secret darksky_api
  # - platform: nws
  #   api_key: !secret nws_api_key
  #   station: klzu

conversation:

device_tracker:
  # - platform: icloud
  #   username: !secret ICLOUD_USER
  #   password: !secret ICLOUD_PASS
  #   track_new_devices: yes
  # - platform: owntracks
  # 
  # - platform: eero_tracker
  #   consider_home: 300
  #   interval_seconds: 60
  #   track_new_devices: yes
  #   only_macs: "d0:c5:f3:80:50:5e, f4:31:c3:84:1d:d1, 08:74:02:CC:C4:97, 5C:F5:DA:9B:5A:A2, 34:7C:25:CC:9D:0F, 64:52:99:93:F1:B3"

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

# arlo:
#   username: !secret arlo_user
#   password: !secret arlo_pass

alarm_control_panel:
  # - platform: arlo
  #   home_mode_name: home
  #   away_mode_name: armed
  - platform: aarlo
    home_mode_name: home
    away_mode_name: Armed

# Using the HACS Arlo Integration 
aarlo:
  host: https://my.arlo.com
  username: !secret arlo_user
  password: !secret arlo_pass
  db_motion_time: 30
  db_ding_time: 10
  recent_time: 10
  last_format: '%m-%d %H:%M'
  refresh_devices_every: 2
  verbose_debug: True
  
speedtestdotnet:


discovery:
  ignore:
    - igd
    - homekit

updater:
  include_used_components: true

sun:

recorder:
  #db_url: sqlite:///data/home-assistant_v2.db
  purge_keep_days: 2
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sun.sun # Don't record sun data
      - sensor.last_boot # Comes from 'systemmonitor' sensor platform
      - sensor.date


logbook:
  include:
    domains:
      - media_player
      - automation
      - script

logger:
  default: warning
  #logs:
 
  #   homeassistant.components.sensor.alpha_vantage: debug


history:
  include:
    domains:
      - sensor
      - switch
      - media_player
      - light

camera:
  - platform: mjpeg
    name: Garage Door Cam 
    mjpeg_url: !secret garage_cam
  - platform: aarlo
    ffmpeg_arguments: '-pred 1 -q:v 2'
    
ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg   

life360:
  accounts:
    - username: !secret life360_username
      password: !secret life360_password

python_script:

ecobee:
  api_key: !secret ecobee_api

map:

wwlln:

geo_location:
  - platform: usgs_earthquakes_feed
    feed_type: 'past_hour_all_earthquakes'

gdacs:
  categories:
    - Earthquake
    - Tropical Cyclone
  radius: 500
  latitude: !secret MY_LATITUDE
  longitude: !secret MY_LONGITUDE


tplink:
  discovery: false
  switch:
    - host: 192.168.7.105
    - host: 192.168.7.107
    - host: 192.168.7.116
    - host: 192.168.7.120
    - host: 192.168.7.136
    - host: 192.168.7.137

wyzeapi:
  username: !secret wyze_user
  password: !secret wyze_password

ifttt:
  key: !secret IFTTT_API_KEY 

# media_player:
#   - platform: spotify
#     client_id: !secret spotify_client
#     client_secret: !secret spotify_secret

media_extractor:

group: !include groups.yaml

proximity:
  home_jeff:
    devices:
      - device_tracker.life360_jeffrey_stone
    zone: home
    tolerance: 5
    unit_of_measurement: mi
  home_kat:
    devices:
      - device_tracker.life360_kat_stone
    zone: home
    tolerance: 5
    unit_of_measurement: mi
  home:
    devices:
      - device_tracker.life360_jeffrey_stone
      - device_tracker.life360_kat_stone
    zone: home
    tolerance: 5
    unit_of_measurement: mi

# Using the HACS Daily Snapshot Clean Up Plugin 
clean_up_snapshots_service:
  host: !secret snapshot_url
  token: !secret snapshot_token
  number_of_snapshots_to_keep: 3
 
homekit:
  filter:
    include_domains:
      - light
    include_entities:
      - switch.craft_room_fan
      - switch.driveway_light
      - switch.incense
      - switch.living_room_fan
      - switch.rail_lights
      - switch.spotlight
      - switch.upstairs
      - switch.upstairs_fan
      - switch.artemis
      - switch.fireplace_lights
      - switch.desk
      - switch.forest
      - switch.front_porch
      - switch.ha_speaker
      - input_boolean.house_party_protocol
      - switch.christmas_tree
      - switch.0xf0d1b80000052281_switch
      - switch.garage_fan
      

### Includes ###
alert: !include_dir_merge_named alerts/
automation: !include automations.yaml
script: !include_dir_merge_named scripts
#group: !include groups.yaml
#automation: !include automations.yaml
sensor: !include_dir_merge_list sensors
binary_sensor: !include_dir_merge_list binary_sensors
#light: !include_dir_merge_list lights
light: !include lights.yaml
#switch: !include_dir_merge_list switches
switch: !include switches.yaml
#script: !include_dir_merge_named scripts
#intent_script: !include intents/intents.yaml
scene: !include scenes.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml
zone: !include zones.yaml
