### Views ###
default_view:
    name: Home
    view: yes
    icon: mdi:home
    entities:

      


#################################################################################
### Grops ###

House Conditions:
  - climate.first_floor
  - sensor.accurite_back_porch_temperature
  - sensor.accurite_back_porch_humidity
  - sensor.accurite_garage_temperature
  - sensor.accurite_garage_humidity

Outside Lights:
  - switch.driveway_light
  - switch.front_porch
  - light.side_door_light
  
External Doors:
  - binary_sensor.side_door
  - binary_sensor.front_door
  - binary_sensor.back_door
  - binary_sensor.laundry_room_door
  - binary_sensor.garage_door

Garage Doors:
  - binary_sensor.side_door
  - binary_sensor.garage_door

Internal Doors:
  - binary_sensor.attic_door

Disney Audio:
  - input_boolean.tiki_room_audio
  - input_boolean.happy_ever_after_show
  - input_boolean.haunted_mansion
  - input_boolean.boo_to_you_show
  - input_boolean.spaceship_earth_ride
  - input_boolean.mk_loop
  - input_boolean.illuminations
  - input_boolean.boo_to_you
  - input_boolean.happy_ever_after

rgb lr:
  - light.0xb0ce18140003608a_light
  - light.0xb0ce181400051b4c_light_2
  - light.0xb0ce181400051072_light_2

incense:
  - switch.incense
  - switch.artemis
  - switch.forest

all fans:
  - switch.upstairs_fan
  - switch.living_room_fan

Skylars Bedroom:
  - light.0xe20db9fffe003637_light
  - switch.0xf0d1b80000052281_switch

Master Bedroom:
  - light.0xe20db9fffe004207_light


