

#################################################################################
### Grops ###

Family:
  - person.jeffrey
  - person.katherine

arriving:
  name: Arriving
  entities: []


House Conditions:
  - climate.first_floor
  - sensor.accurite_back_porch_temperature
  - sensor.accurite_back_porch_humidity
  - sensor.accurite_garage_temperature
  - sensor.accurite_garage_humidity

Outside Lights:
  - switch.driveway_light
  - switch.front_porch_light
  - light.side_door_light
  
External Doors:
  - binary_sensor.side_door
  - binary_sensor.front_door
  - binary_sensor.back_door
  - binary_sensor.laundry_door
  - binary_sensor.garage_door

Garage Doors:
  - binary_sensor.side_door
  - binary_sensor.garage_door

Internal Doors:
  - binary_sensor.attic_door

rgb lr:
  - light.0xb0ce18140003608a_light
  - light.0xb0ce181400051072_light
  - light.0xb0ce181400051b4c_light

livingroom tower:
  - light.0xb0ce18140003608a_light

livingroom lamps:
  - light.0xb0ce181400051072_light
  - light.0xb0ce181400051b4c_light

incense:
  - switch.incense
  - switch.artemis
  - switch.forest

all fans:
  - switch.croft_fan
  - switch.livingroom_fan

Skylars Bedroom:
  - light.0xb0ce18140003b334_light # skylars tower
  - switch.0xf0d1b80000052281_switch # rainbow light
  - light.0xb0ce1814035bb3f0_light # skylars spotlight
  - light.wled_loftbed

Master Bedroom:
  - light.jeff_lamp

kitchen:
  - light.kitchen_cabinets
  - switch.ha_speaker

livingroom:
  - light.0xb0ce18140003608a_light
  - light.0xb0ce181400051072_light
  - light.0xb0ce181400051b4c_light
  - switch.fireplace_lights
  - switch.rail_lights

theater lights:
  - light.theater_light

Chores:
  - input_boolean.clean_litterbox
  - input_boolean.heartworm
  - input_boolean.nextguard
  - input_boolean.clean_washer
  - input_boolean.clean_dishwasher
  - input_boolean.clean_towel_day
  - input_boolean.clean_sheet_day
  - input_boolean.clean_kitchen
  - input_boolean.clean_livingroom
  - input_boolean.clean_bathrooms
  - input_boolean.mow_yard
  - input_boolean.replace_hvac_filter