

#################################################################################
### Grops ###

Family:
  - person.jeffrey
  - person.katherine

arriving:
  name: Arriving
  entities: []

House Conditions:
  - climate.first_floor
  - sensor.accurite_back_porch_temperature
  - sensor.accurite_back_porch_humidity
  - sensor.accurite_garage_temperature
  - sensor.accurite_garage_humidity

occupancy:
  - binary_sensor.kitchen_occupancy
  - binary_sensor.living_room_occupancy
  - binary_sensor.master_bedroom_occupancy
  - binary_sensor.skylar_room_occupancy
  - binary_sensor.croft_occupancy
  - binary_sensor.theater_occupancy

audio_devices:
  - media_player.kitchen_display
  - media_player.upstairs_speaker
  - media_player.master_bedroom_speaker

Outside Lights:
  - switch.driveway_light
  - switch.front_porch_light
  - light.cree_side_door_light
  
External Doors:
  - binary_sensor.side_door
  - binary_sensor.front_door
  - binary_sensor.back_door
  - binary_sensor.laundry_door
  - binary_sensor.garage_door

Garage Doors:
  - binary_sensor.side_door
  - binary_sensor.garage_door

Internal Doors:
  - binary_sensor.attic_door

rgb lr:
  - light.front_door_lamp_level_light_color_on_off
  - light.living_room_lamp
  - light.living_room_tower_lamp_level_light_color_on_off

livingroom tower:
  - light.living_room_tower_lamp_level_light_color_on_off

livingroom lamps:
  - light.living_room_lamp
  - light.front_door_lamp_level_light_color_on_off

incense:
  - switch.incense
  - switch.artemis
  - switch.forest_incense_on_off

all fans:
  - switch.croft_fan
  - switch.livingroom_fan

Skylars Bedroom:
  - switch.forest # skylars tower
  - switch.rainbow_light_on_off # rainbow light
  - light.wled_loftbed

Master Bedroom:
  - light.jeff_lamp
  - switch.kat_lamp_on_off


kitchen:
  - light.kitchen_cabinets
  - switch.ha_speaker

livingroom:
  - light.front_door_lamp_level_light_color_on_off
  - light.living_room_lamp
  - light.living_room_tower_lamp_level_light_color_on_off
  - switch.fireplace_lights
  - switch.rail_lights

theater lights:
  - light.theater_light

Chores:
  - input_boolean.clean_litterbox
  - input_boolean.heartworm
  - input_boolean.nextguard
  - input_boolean.clean_washer
  - input_boolean.clean_dishwasher
  - input_boolean.clean_towel_day
  - input_boolean.clean_sheet_day
  - input_boolean.clean_kitchen
  - input_boolean.clean_livingroom
  - input_boolean.clean_bathrooms
  - input_boolean.mow_yard
  - input_boolean.replace_hvac_filter