

#################################################################################
### Grops ###

House Conditions:
  - climate.first_floor
  - sensor.accurite_back_porch_temperature
  - sensor.accurite_back_porch_humidity
  - sensor.accurite_garage_temperature
  - sensor.accurite_garage_humidity

Outside Lights:
  - switch.driveway_light_2
  - switch.front_porch_light
  - light.side_door_light_2
  
External Doors:
  - binary_sensor.side_door_contact
  - binary_sensor.front_door_contact
  - binary_sensor.back_door_contact
  - binary_sensor.laundry_door_contact
  - binary_sensor.garage_door_contact

Garage Doors:
  - binary_sensor.side_door_contact
  - binary_sensor.garage_door_contact

Internal Doors:
  - binary_sensor.attic_door_contact



rgb lr:
  - light.livingroom_tower
  - light.livingroom_lamp_1
  - light.livingroom_lamp_2

incense:
  - switch.incense
  - switch.artemis
  - switch.forest

all fans:
  - switch.croft_fan
  - switch.livingroom_fan

Skylars Bedroom:
  - light.skylars_lamp
  - switch.rainbow_light
  - light.skylars_spotlight
  - light.skylars_tower

Master Bedroom:
  - light.jeff_lamp


