automations:
  name: Automations
  icon: mdi:home-automation
trash_notification:
  name: Trash Notification
  icon: mdi:telegram
welcome_greeting:
  name: Welcome Greeting
  icon: mdi:speaker-wireless
lockdown_notification:
  name: Lockdown Notifications
  icon: mdi:speaker-wireless
garage_notifications:
  name: Garage Notifications
  icon: mdi:speaker-wireless
tornado_alarm:
  name: Tornado Alarm
  icon: mdi:speaker-wireless
tstorm_alarm:
  name: T-Storm Alarm
  icon: mdi:speaker-wireless
text_notify_jeff:
  name: Send Jeff Texts
  icon: mdi:telegram
text_notify_kat:
  name: Send Kat Texts
  icon: mdi:telegram
audible_notifications:
  name: Audible Notifications
  icon: mdi:speaker-wireless
presence_notifications_jeff:
  name: Send Jeff Presence Texts
  icon: mdi:telegram
presence_notifications_kat:
  name: Send Kat Presence Texts
  icon: mdi:telegram
kat_heading_home:
  name: Kat Heading Home
  icon: mdi:car
jeff_heading_home:
  name: Jeff Heading Home
  icon: mdi:car
jeff_traffic_alerts:
  name: Jeff Traffic Alerts
  icon: mdi:bell-plus
jeff_traffic_alert_home:
  name: Jeff Traffic Alert Home
  icon: mdi:traffic-light
tornado_watch:
  name: Tornado Watch
  icon: mdi:message-alert
kat_travel_monitor:
  name: Kat Travel Monitor
  icon: mdi:car
jeff_travel_monitor:
  name: Jeff Travel Monitor
  icon: mdi:car
notifications_audio:
  name: Audio Notifications
  icon: mdi:speaker-wireless
text_notifications:
  name: Text Notifications
  icon: mdi:telegram
presence_text_notifications:
  name: Presence Texts
  icon: mdi:telegram
presence_audio_notifications:
  name: Presence Audio
  icon: mdi:speaker-wireless
weather_reports:
  name: Weather Info 
traffic_reports:
  name: traffic_reports
sun_reports:
  name: Sun Reports 
new_ha_announcement:
  name: New HA Announcement
  icon: mdi:twitter
showing_now:
  name: Showing Now
  icon: mdi:popcorn
skylar_school:
  name: Skylar at School
shuffle_spotify:
  name: Spotify Shuffle


#####################
# Chore List
#####################
# Everyday
feed_fish:
  name: Feed Fish 
  icon: mdi:fishbowl
wash_dishes:
  name: Wash Dishes 
  icon: mdi:dishwasher

# Monday | Wednesday | Friday
clean_litterbox:
  name: Clean Litterbox
  icon: mdi:cat 

# Monday
clean_towel_day:
  name: Clean Towel Day  


# Tuesday
vacuum:
  name: Vavuum Living Room
 
dust:
  name: Dust 
  
mop_kitchen:
  name: Mop Kitchen  
  
 



# Friday
clean_sheet_day:
  name: Clean Sheet Day   
 


# Weekend 
clean_kitchen:
  name: Clean Kitchen
clean_bathrooms:
  name: Clean Bathrooms 
mow_yard:
  name: Mow Yard 

# Sunday
menu_day:
  name: Menu Day 

# Monthly
wash_mattress_protector:
  name: Wash Mattress Protector 

clean_fish_tank:
  name: Clean Fish Tank 

heartworm:
  name: Heartworm
  icon: mdi:dog-side
