- name: all lights on
  entities:
    light.kitchen_cabinets:
      state: 'on'
      brightness: 100
    light.kitchen_cabinet_lights:
      state: 'on'
    switch.upstairs:
      state: 'on'
    group.rgb_lr:
      state: 'on'
      brightness_pct: 100
      rgb_color: [255,255,255]
    switch.fireplace_lights:
      state: 'on'
    light.0xe20db9fffe004207_light:
      state: 'on'
      brightness: 100
    light.0xe20db9fffe003637_light:
      state: 'on'
      brightness: 100
    switch.0xf0d1b80000052281_switch:
      state: 'on'
    switch.rail_lights:
      state: 'on'
    light.0xb0ce18140003b334_light:
      state: 'on'
      brightness: 100
    light.0xb0ce1814035bb3f0_light:
      state: 'on'
      brightness: 100


- name: normal livingroom lighting
  entities:
    group.rgb_lr:
      state: 'on'
      brightness: 255
      color_temp: 369
      rgb_color: [255,255,255]
    # light.front_door_lamp:
    #   state: 'on'
    #   brightness: 255
    # light.living_room_lamp:
    #   state: 'on'
    #   brightness: 250

- name: dimished livingroom lighting
  entities:
    light.livingroom_tower:
      state: 'on'
      brightness: 40
      color_temp: 369
    group.livingroom_lamps:
      state: 'off'
    switch.fireplace_lights:
      state: 'off'

- name: illuminations livingroom lighting two
  entities:
    light.tower_lamp_2:
      state: 'on'
      brightness: 40
      color_temp: 369
    light.front_door_lamp:
      state: 'on'
      brightness: 40
      color_temp: 369
    light.living_room_lamp:
      state: 'off'
    switch.fireplace_lights:
      state: 'off'

- name: illuminations livingroom lighting three
  entities:
    light.tower_lamp_2:
      state: 'on'
      brightness: 40
      color_temp: 369
    light.front_door_lamp:
      state: 'on'
      brightness: 40
    light.living_room_lamp:
      state: 'on'
      brightness: 40
      color_temp: 369
    switch.fireplace_lights:
      state: 'off'

# light.0xb0ce18140003608a_light = Tower Lamp
# light.0xb0ce181400051072_light_2 = Front Door Lamp
# light0xb0ce181400051b4c_light_2 = Table Lampo

- name: night time livingroom lighting
  entities:
    group.livingroom_tower:
      state: 'on'
      brightness: 10
      color_temp: 369
    group.livingroom_lamps:
      state: 'off'
    switch.fireplace_lights:
      state: 'off'

- name: livingroom lighting off
  entities:
    group.livingroom_tower:
      state: 'off'
    group.livingroom_lamps:
      state: 'off'
    switch.fireplace_lights:
      state: 'off'

- name: diminished kitchen lighting
  entities:
    light.kitchen_cabinets:
      state: 'on'
      brightness: 10
    switch.ha_speaker:
      state: 'off'

- name: normal kitchen lighting
  entities:
    light.kitchen_cabinets:
      state: 'on'
      brightness: 250
    switch.ha_speaker:
      state: 'on'

- name: kitchen lighting off
  entities:
    light.kitchen_cabinets:
      state: 'off'
    switch.ha_speaker: #Need to rename
      state: 'off'

- name: lights out
  entities:
    light.kitchen_cabinets:
      state: 'off'
    switch.ha_speaker:
      state: 'off'
    switch.croft_light:
      state: 'off'
    group.rgb_lr:
      state: 'off'
    switch.fireplace_lights:
      state: 'off'
    group.skylars_bedroom:
      state: 'off'
    group.master_bedroom:
      state: 'off'
    switch.rail_lights:
      state: 'off'


- name: haunted preshow
  entities:
    group.kitchen:
      state: 'off'
    switch.fireplace_lights:
      state: 'off'
    group.rgb_lr:
      state: 'on'
      brightness: 255
    switch.rail_lights:
      state: 'off' 

- name: haunted lights out
  entities:
    group.kitchen:
      state: 'off'
    group.livingroom:
      state: 'off'
    

- name: wishes preshow
  entities:
    switch.ge_14291_in_wall_smart_switch_switch_2:
      state: 'off'
    group.rgb_lr:
      state: 'off'
    switch.fireplace_lights:
      state: 'off'
    switch.rail_lights:
      state: 'on'
    switch.christmas_tree:
      state: 'off'

- name: wishes show
  entities:
    switch.christmas_tree:
      state: 'on'
    light.0xb0ce181400051b4c_light:
      state: 'on'
      brightness: 20
    light.0xb0ce18140003608a_light:
      state: 'on'
      brightness: 20
    light.0xb0ce181400051072_light:
      state: 'on'
      brightness: 20

- name: table lamp blue
  entities:
    group.livingroom_lamps:
      state: 'on'
      brightness_pct: 100
      rgb_color: [65,105,255]

- name: tower lamp red
  entities:
    group.livingroom_tower:
      state: 'on'
      brightness_pct: 100
      rgb_color: [255,40,0]
    
- name: front lamp green
  entities:
    group.livingroom_lamps:
      state: 'on'
      brightness_pct: 100
      rgb_color: [0,128,0]

- name: master bedroom on
  entities:
    light.jeff_lamp:
      state: 'on'
      brightness: 255
    switch.0xbc33acfffe217d35_switch:
      state: 'on'
    light.0xb0ce1814035bb3f0_light:
      state: 'on'
      brightness: 77

- name: master bedroom off
  entities:
    light.jeff_lamp:
      state: 'off'
    switch.0xbc33acfffe217d35_switch:
      state: 'off'
    light.0xb0ce1814035bb3f0_light:
      state: 'off'
      
- name: master bedroom dim
  entities:
    light.0xb0ce1814035bb3f0_light:
      state: 'on'
      brightness: 38
    switch.0xbc33acfffe217d35_switch:
      state: 'off'
    light.jeff_lamp:
      state: 'off'
    

- name: santa protocol
  entities:
    switch.christmas_tree:
      state: 'on'
    switch.rail_lights:
      state: 'on'
    
- name: skylar room prebed
  entities:
    switch.forest:
      state: 'on'
    light.wled_loftbed:
      state: 'on'
      brightness: 255
      rgb_color: [63, 255, 0]
    switch.0xf0d1b80000052281_switch:
      state: 'on'
    

- name: skylar room sleep
  entities:
    input_boolean.audible_notifications:
      state: 'off'
    light.wled_loftbed:
      state: 'on'
      brightness_pct: 100
      rgb_color: [63, 255, 0]
    switch.0xf0d1b80000052281_switch:
      state: 'on'
    switch.wled_loftbed_nightlight:
      state: 'on'
    switch.forest:
      state: 'off'

- name: skylar room morning
  entities:
    switch.forest:
      state: 'on'

- name: skylar room day
  entities:
    switch.forest:
      state: 'off'
    switch.0xf0d1b80000052281_switch:
      state: 'off'


      
- name: jeff desk on
  entities:
    light.0xb0ce18140003b334_light:
      state: 'on'
      brightness: 204
    light.0xb0ce1814035bb3f0_light:
      state: 'on'
      brightness: 77

- name: jeff desk off
  entities:
    light.0xb0ce18140003b334_light:
      state: 'off'
    light.0xb0ce1814035bb3f0_light:
      state: 'off'
      



#########################################
# Haunted Manshion show scenes
#
# These scenes are used in the Haunted Mansion show that
# takes place when requested

- name : lr_cool_white
  entities:
    group.rgb_lr:
      state: 'on'
      brightness: 255
      rgb_color: [255,255,255]

- name : lr_blue
  entities:
    group.rgb_lr:
      state: 'on'
      brightness: 255
      color_name: "blue"

- name : lr_red
  entities:
    group.rgb_lr:
      state: 'on'
      brightness: 255
      rgb_color: [255,40,0]


#######################################
# Home Audio

- name: normal audio
  entities:
    media_player.tsr_6750_a3ed2f:
      state: 'on'
      source: HDMI1

- name: quiet audio
  entities:
    media_player.tsr_6750_a3ed2f:
      state: 'off'

#######################################
# Home Theather

- name: theater dark
  entities:
    group.theater_lights:
      state: 'off'

- name: theater dim
  entities:
    group.theater_lights:
      state: 'on'
      brightness: 40

- name: theater bright
  entities:
    group.theater_lights:
      state: 'on'
      brightness: 255

#######################################
# Skylar
# - name: Skylar Full
#   entities:
#     input_number.skylar_tv_time: 120
#     input_number.skylar_ps_time: 120
#     input_number.skylar_yt_time: 60

# - name: Skylar restricted
#   entities:
#     input_number.skylar_tv_time: 0
#     input_number.skylar_ps_time: 0
#     input_number.skylar_yt_time: 0

# - name: Skylar Limited
#   entities:
#     input_number.skylar_tv_time: 60
#     input_number.skylar_ps_time: 60
#     input_number.skylar_yt_time: 0
