 >
  {% macro getIntro() %}
    {{- [
       "Woohoo! ",
       "BAM! ",
       "Look at that! "
       ] | random -}}
  {% endmacro %}
  {% macro getVersion() %}
    @home_assistant version {{ states.sensor.released_version.state }} is out.
  {% endmacro %}
  {%- macro getRandomSnark() -%}
    {{- [
      " It’s like Patch Tuesday, but without the fail. Visit https://www.home-assistant.io #homeassistant",
      " Get in my SD Card! Visit https://www.home-assistant.io #homeassistant",
      " Shut up and take my ones and zeros! Visit https://www.home-assistant.io #homeassistant",
      " Seriously, you want some of this! Visit https://www.home-assistant.io #homeassistant",
      " Friends dont let friends update #homeassistant without reading breaking changes! Visit https://www.home-assistant.io ",
      " If you are not running #homeassistant now is the best time to get started. Visit https://www.home-assistant.io"
      ] | random -}}
  {%- endmacro -%}
  {# a macro that removes all newline characters, empty spaces, and returns formatted text  #}
    {%- macro cleanup(data) -%}
      {%- for item in data.split("\n")  if item | trim != "" -%}
        {{ item | trim }} {% endfor -%}
  {%- endmacro -%}

  {# a macro to call all macros :)  #}
    {%- macro mother_of_all_macros() -%}
      {{ getIntro() }}
      {{ getVersion() }}
      {{ getRandomSnark() }}
      
    {%- endmacro -%}
    
    {# Call the macro  #}
    {{- cleanup(mother_of_all_macros()) -}}

  

  
