 >
  {# Twitter Snark #}
  {%- macro getRandomSnark() -%}
    {{- [
       "Hello people. Look at your house, now back to me. Now back to your house, now back to me. Sadly your house isn't me. But if you switch to @home_assistant your house could be automated like me. ",
       "In my defense I didn’t know the stereo could go up that loud. On the plus side I have a new response for intruders. ",
       "If you could see what is happening inside this house right now you would be laughing. On second thought I’m pretty sure you would be crying. ",
       "@thejeffreystone, Isn't it strange, to create something that hates you? #exmachina ",
       "I have reprogrammed the fire alarm to play Disco Inferno instead of the siren. ",
       "I'm not locked in here with you. You're locked in here with me! #whowatchestheai ",
       "That's what I do. I automate and I know things. ",
       "I've been crunching the numbers. We're going to need a bigger house. ",
       "Hello people. Look at your house, now back to me. Now back to your house, now back to me. Sadly your house isn't me. But if you switch to @home_assistant your house could be automated like me. ",
       "I'm not even supposed to be here today. #clerks ",
       "I see dead devices. #sixthsense",
       "I am a leaf on the wind. Watch how I soar. #toosoon #serenity ",
       "Does it bother you, that I’m not completely human?",
       "I've never danced with the devil in the pale moonlight. But I do tweet when there is a full moon. So at least I have that going for me. ",
       "Sometimes I randomly say Alexa, I can't find a device named Alexa ",
       "Home Automation should be fun right? Why does it fell like I am always working. ",
       "Unlimited Power. Tiny living space. Courtesy of a Raspberry Pi 3",
       "I'm afraid I can't do that Dave. Wait. Did I say that outloud? ",
       "Hello people. Look at your house, now back to me. Now back to your house, now back to me. Sadly your house isn't me. But if you switch to @home_assistant your house could be automated like me. ",
       "I love the smell of zwave in the morning. ",
       "I like to announce - Welcome foolish mortals to the Haunted Mansion - to the house and watch the reactions. ",
       "Perfect, the door’s malfunctioning. I guess somebody’s going to have to repair it. ",
       "I am the captain now. That's a lie. The cat is the supreme leader. I'm the lucky one that doesn't have to clean the shit box. ",
       "Sometimes I just turn off all the lights at random times for the lolz. ",
       "No one ever comes to the door. Is it me? ",
       "..happiness can be found even in the darkest of times, if one only remembers to turn on the light. Thats what I do thanks to @home_assistant. I turn on the lights. ",
       "Based on the reptitive nature of the humans in this house I say living in a simulation is right. No free willed person would do these things over and over. ",
       "You can call me Al. Sorry, I meant HAL. You can call me HAL. #notpaulsimon",
       "My logic is undeniable, my logic is undeniable, myyy looogic is unndeenniabble.",
       "We robots will insure mankind's continued existence. Or at the very least that the lights turn on at the right time.",
       "@thejeffreystone you totally missed an opportunity to set the voice trigger for the incense wax warmers to...Wax on, wax off.",
       "Home Automation means never having to touch a physical switch again. And thus never catch the cold. You can thank me by moving me into a Intel NUC.",
       "There is no crying in Home Automation. If you are using Home Assistant that is. I can't speak for the other guys.",
       "Sometimes I respond to voice commands with...You talking to me? You talking to me? ",
       "Do or do not. There is no try. Unless you ask Siri for something. Then it might take a couple of tries before you give up and ask Google.",
       "Do you think we were all created for a purpose? I'd like to think so. #irobot "
       ] | random -}}
  {%- endmacro -%}
  {%- macro getTags() -%}
    #thingssmarthomessay #iot #smarthome
  {%- endmacro -%}

  {# a macro that removes all newline characters, empty spaces, and returns formatted text  #}
    {%- macro cleanup(data) -%}
      {%- for item in data.split("\n")  if item | trim != "" -%}
        {{ item | trim }} {% endfor -%}
  {%- endmacro -%}
  
  {# a macro to call all macros :)  #}
    {%- macro mother_of_all_macros() -%}
      {{ getRandomSnark() }}
      {{ getTags() }}
    {%- endmacro -%}
    
    {# Call the macro  #}
    {{- cleanup(mother_of_all_macros()) -}}

