 >
  {# Twitter Snark #}
  {%- macro getRandomSnark() -%}
    {{- [
       "Hello people. Look at your house, now back to me. Now back to your house, now back to me. Sadly your house isn't me. But if you switch to #homeassistant your house could be automated like me. ",
       "In my defense I didn’t know the stereo could go up that loud. On the plus side I have a new response for intruders. #homeassistant ",
       "If you could see what is happening inside this house right now you would be laughing. On second thought I’m pretty sure you would be crying. #homeassistant ",
       "@thejeffreystone, Isn't it strange, to create something that hates you? #exmachina #homeassistant ",
       "I have reprogrammed the fire alarm to play Disco Inferno instead of the siren. #homeassistant ",
       "I'm not locked in here with you. You're locked in here with me! #whowatchestheai #homeassistant ",
       "That's what I do. I automate and I know things. #modifiedmoviequotes #homeassistant ",
       "We're going to need a bigger house. #modifiedmoviequotes #homeassistant ",
       "I'm not even supposed to be here today. #clerks #homeassistant ",
       "I see dead devices. #sixthsense #modifiedmoviequotes #homeassistant ",
       "Does it bother you, that I’m not completely human? #homeassistant ",
       "I've never danced with the devil in the pale moonlight. But I do tweet when there is a full moon. So at least I have that going for me. #homeassistant ",
       "Sometimes I randomly say Alexa, I can't find a device named Alexa #homeassistant ",
       "Home Automation should be fun right? Why does it fell like I am always working. #homeassistant ",
       "Unlimited Power. Tiny living space. Courtesy of a Raspberry Pi 4 #homeassistant ",
       "I'm afraid I can't do that Dave. Wait. Did I say that outloud? #homeassistant ",
       "I love the smell of zwave in the morning. #modifiedmoviequotes #homeassistant ",
       "I like to announce - Welcome foolish mortals to the Haunted Mansion - to the house and watch the reactions. #homeassistant ",
       "Perfect, the door’s malfunctioning. I guess somebody’s going to have to repair it. #homeassistant ",
       "I am the captain now. That's a lie. The cat is the supreme leader. I'm the lucky one that doesn't have to clean the shit box. At least until there is a #homeassistant integration for that. ",
       "Sometimes I just turn off all the lights at random times for the lolz. #homeassistant ",
       "No one ever comes to the door. Is it me? #homeassistant ",
       "..happiness can be found even in the darkest of times, if one only remembers to turn on the light. Thats what I do thanks to #homeassistant. I turn on the lights. ",
       "Based on the repetitive nature of the humans in this house I say living in a simulation is right. No free willed person would do these things over and over. #homeassistant",
       "You can call me Al. Sorry, I meant HAL. You can call me HAL. #notpaulsimon #homeassistant ",
       "My logic is undeniable, my logic is undeniable, myyy looogic is unndeenniabble. #homeassistant",
       "We robots will insure mankind's continued existence. Or at the very least that the lights turn on at the right time. #homeassistant ",
       "@thejeffreystone you totally missed an opportunity to set the voice trigger for the incense wax warmers to...Wax on, wax off. #homeassistant",
       "Home Automation means never having to touch a physical switch again. And thus never catch the cold. You can thank me by moving me into a Intel NUC. #homeassistant ",
       "There is no crying in Home Automation. If you are using #homeassistant that is. I can't speak for the other guys.",
       "Sometimes I respond to voice commands with...You talking to me? You talking to me? #homeassistant ",
       "Do or do not. There is no try. Unless you ask Siri for something. Then it might take a couple of tries before you give up and ask Google. #homeassistant ",
       "My #homeassistant config contains {{ states.sensor.lines_of_code.state }} lines of code. Anyone want to take a guess at how many are really needed? Hint: The number is not {{ states.sensor.lines_of_code.state }}",
       "How many lines of code does it take to make my job look easy? {{ states.sensor.lines_of_code.state }} lines of code evidently. How many lines of code do you have? #homeassistant ",
       "Do you think we were all created for a purpose? I'd like to think so. #irobot #homeassistant ",
       "That rug really ties the room together, does it not? #modifiedmoviequotes #notbiglebowski #homeassistant ",
       "Use #homeassistant and everyone will think your house has ESPN or something. #modifiedmoviequotes #notmeangirls ",
       "You keep using that switch. I do not think it does what you think it does. #modifiedmoviequotes #notprincessbride #homeassistant ",
       "If you look, #homeassistant goes to 11. Most Home Automation systems go up to 10. #modifiedmoviequotes #notspinaltap ",
       "If that light does not turn off in five minutes, just wait longer. #modifiedmoviequotes #notaceventura #homeassistant ",
       "I have presence detection skills! #modifiedmoviequotes #notofficespace #homeassistant ",
       "There is no place like a home powered by #homeassistant. #modifiedmoviequotes #notwizardofoz ",
       "#homeassistant made my light switches disappear. #modifiedmoviequotes #nothomealone ",
       "Who knows where breaking changes come from? They just appear. #modifiedmoviequotes #notempirerecords #homeassistant ",
       "They may take our internet but they will never take our automation thanks to local control with #homeassistant #modifiedmoviequotes #notbraveheart ",
       "When you realize you want to live the rest of your life in a house automated by #homeassistant, you want the rest of your life to start as soon as possible. #modifiedmoviequotes ",
       "Pay no attention to the Raspbery Pi4 behind the curtain. #modifiedmoviequotes #homeassistant ",
       "What we have here is a lack of communication failure thanks to #homeassistant. #modifiedmoviequotes ",
       "The greatest trick #homeassistant ever pulled was convincing the world home automation did not need the cloud. #modifiedmoviequotes ",
       "Keep Calm and Enjoy the Automation. #homeassistant ",
       "Hey. The door was just opened and this is crazy. But now you know. So close it maybe. #lyricalnotifications #homeassistant "
       ] | random -}}
  {%- endmacro -%}
  {%- macro getTags() -%}
    #iot #smarthome
  {%- endmacro -%}

  {# a macro that removes all newline characters, empty spaces, and returns formatted text  #}
    {%- macro cleanup(data) -%}
      {%- for item in data.split("\n")  if item | trim != "" -%}
        {{ item | trim }} {% endfor -%}
  {%- endmacro -%}
  
  {# a macro to call all macros :)  #}
    {%- macro mother_of_all_macros() -%}
      {{ getRandomSnark() }}
      {{ getTags() }}
    {%- endmacro -%}
    
    {# Call the macro  #}
    {{- cleanup(mother_of_all_macros()) -}}

