 >
  {# Twitter Promos #}
  {%- macro getRandomIntro() -%}
    {{- [
       "Do you want your house to be a #smarthome? ‏",
       "Your house can be a #smarthome too. ",
       "Transform your home into a #smarthome. ",
       "You get a #smarthome and you get a smarthome and you get a smarthome. ",
       "Looking to automate your house? ",
       "Want to get into Home Automation? "
       ] | random -}}
  {%- endmacro -%}
  {%- macro getRandomLead() -%}
    {{- [
       "All you need is #home_assistant, and these config files ->‏",
       "Just grab @home_assistant and checkout ",
       "Just grab #home_assistant and for inspiration checkout ",
       "It is easy. Install #home_assistant, and add some config files like ",
       "You can't go wrong with #home_assistant. For an example of what you can do checkout "
       ] | random -}}
  {%- endmacro -%}
  {%- macro getRandomPromo() -%}
    {{- [
       "https://github.com/CCOSTAN/Home-AssistantConfig#logo cc: @ccostan ‏",
       "https://github.com/skalavala/mysmarthome ",
       "https://github.com/thejeffreystone/home-assistant-configuration cc: @thejeffreystone ",
       "https://github.com/arsaboo/homeassistant-config ",
       "https://github.com/Vasiley/Home-Assistant-Main ",
       "https://github.com/JamesMcCarthy79/Home-Assistant-Config ",
       "https://github.com/bruhautomation/BRUH3-Home-Assistant-Configuration cc: @BRUHautomation ",
       "https://github.com/isabellaalstrom/home-assistant-config cc: @teachingbirds ",
       "https://github.com/JuanMTech/Home_Assistant_files cc: @JuanMTech ",
       ] | random -}}
  {%- endmacro -%}
  {%- macro getTags() -%}
    #homeassistant #youcandoit #spreadtheword #givingback
  {%- endmacro -%}

  {# a macro that removes all newline characters, empty spaces, and returns formatted text  #}
    {%- macro cleanup(data) -%}
      {%- for item in data.split("\n")  if item | trim != "" -%}
        {{ item | trim }} {% endfor -%}
  {%- endmacro -%}
  
  {# a macro to call all macros :)  #}
    {%- macro mother_of_all_macros() -%}
      {{ getRandomIntro() }}
      {{ getRandomLead() }}
      {{ getRandomPromo() }}
      {{ getTags() }}
    {%- endmacro -%}
    
    {# Call the macro  #}
    {{- cleanup(mother_of_all_macros()) -}}

